CREATE TABLE IF NOT EXISTS USUARIOS(
	USUARIO VARCHAR(10) NOT NULL,
	PASSW VARCHAR(20) NOT NULL,
	CORREO VARCHAR(70) UNIQUE NOT NULL ,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDO VARCHAR(20) NOT NULL,
	ROL VARCHAR (20) NOT null,
	PRIMARY KEY (USUARIO));
	

CREATE TABLE  IF NOT EXISTS INICIATIVAS(
	ID INT UNIQUE NOT NULL,
	VOTOS INT NOT NULL,
	PALABRACLAVE VARCHAR (50) NOT null,
	NOMBRE VARCHAR(50) NOT NULL,
	ESTADO VARCHAR(40) NOT NULL,
	DESCRIPCION VARCHAR(140) NOT NULL,
	AREA VARCHAR(40) NOT NULL,
	USUARIO_I VARCHAR(10) NOT NULL,
	CORREO_I VARCHAR(70)  NOT NULL,
	FECHAR_INI DATE NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_INICIATIVA 
	FOREIGN KEY (USUARIO_I)
	REFERENCES USUARIOS (USUARIO)
	ON UPDATE NO ACTION 
	ON DELETE NO ACTION);
	

CREATE TABLE IF NOT EXISTS COMENTARIOS(
	ID INT NOT NULL,
	IDUSUARIO VARCHAR(10) NOT NULL,
	IDINICIATIVA INT NOT NULL,
	CONTENIDO VARCHAR(300) NOT null,
	FECHA DATE NOT NULL
);



ALTER TABLE COMENTARIOS ADD CONSTRAINT PK_COMENTARIOS PRIMARY KEY(ID,IDUSUARIO,IDINICIATIVA);
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_IDU FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(USUARIO);
ALTER TABLE COMENTARIOS ADD CONSTRAINT FK_COMENTARIOS_IDI FOREIGN KEY(IDINICIATIVA) REFERENCES INICIATIVAS(ID);


CREATE TABLE IF NOT EXISTS VOTOS(
	IDUSUARIO VARCHAR(10) NOT NULL,
	IDINICIATIVA INT NOT NULL
);

ALTER TABLE VOTOS ADD CONSTRAINT PK_VOTOS PRIMARY KEY(IDUSUARIO,IDINICIATIVA);
ALTER TABLE VOTOS ADD CONSTRAINT FK_VOTOS_IDU FOREIGN KEY(IDUSUARIO) REFERENCES USUARIOS(USUARIO);
ALTER TABLE VOTOS ADD CONSTRAINT FK_VOTOS_IDI FOREIGN KEY(IDINICIATIVA) REFERENCES INICIATIVAS(ID);


CREATE TABLE PALABRASCLAVE(
	ID INT NOT NULL,
	IDINICIATIVA INT NOT null,
	PALABRACLAVE VARCHAR(20) UNIQUE NOT NULL
);

ALTER TABLE PALABRASCLAVE ADD CONSTRAINT PK_PALABRASCLAVE PRIMARY KEY(ID,IDINICIATIVA);
ALTER TABLE PALABRASCLAVE ADD CONSTRAINT FK_PALABRASCLAVE_IDI FOREIGN KEY(IDINICIATIVA) REFERENCES INICIATIVAS(ID);

